# Generated by Django 5.1.6 on 2025-12-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('ufc_url', models.URLField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('reach', models.CharField(blank=True, max_length=20, null=True)),
                ('leg_reach', models.CharField(blank=True, max_length=20, null=True)),
                ('octagon_debut', models.CharField(blank=True, max_length=50, null=True)),
                ('fighting_style', models.CharField(default='MMA', max_length=50)),
                ('hometown', models.CharField(blank=True, max_length=120, null=True)),
                ('record', models.CharField(blank=True, max_length=20, null=True)),
                ('striking_accuracy', models.CharField(blank=True, max_length=10, null=True)),
                ('takedown_accuracy', models.CharField(blank=True, max_length=10, null=True)),
                ('significant_strike_defense', models.CharField(blank=True, max_length=10, null=True)),
                ('takedown_defense', models.CharField(blank=True, max_length=10, null=True)),
                ('sig_strikes_landed', models.CharField(blank=True, max_length=10, null=True)),
                ('sig_strikes_absorbed', models.CharField(blank=True, max_length=10, null=True)),
                ('takedown_average', models.CharField(blank=True, max_length=10, null=True)),
                ('submission_average', models.CharField(blank=True, max_length=10, null=True)),
                ('last_3_fights', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='fighters.weightclass')),
            ],
        ),
    ]
