# Generated by Django 5.1.6 on 2026-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_fighter_date_1_fighter_date_2_fighter_date_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='rank_number',
            field=models.IntegerField(null=True),
        ),
    ]
